
<?PHP
$subject = "Neo's Thoughts on Life";
$subjectfolder = "Neos_Thoughts_on_Life196";
$locked = "no";
$nopost = "no";
$post0 = array ("<B>Full Name:</B> Brian Bowden", "<B>Username:</B> <A HREF=../../users/u0000neo/user.php?profile=1><FONT COLOR=$secondarylinkcolor>nEo</FONT></A>", "<B>Position:</B> Administrator", "<B>Date:</B> 11:42:33am, Sunday January 2, 2005", "<B>Post #:</B> 1", "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don't want to get off the internet, but I don't have anything else to do. Well, I do have other things to do, I just don't want to do them. Plus, there's so much internet that you can't possibly get bored. I mean, if you're really bored from the same old sites that you visit every day, you should try some other sites that you've never been to. Just search for something in Google. We're not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don't think y'all would want to run into the same thing. So be careful, and I'll try to do the same.<BR><BR>Let's see, are there any cool new sites that I've been to that y'all might be interested in? No. Are there any sites that I'm going to tell y'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It's NOT a cool site. It's hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn't white I think I would be just a little offended. :-P<BR><BR>The Abrupt End", "11:42:33am, Sunday January 2, 2005", "1104684153");
$posts[0] = $post0;
?>

<?PHP $journalpost = "Neo"; ?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE border=0 width=\"600\"><TR><TD bgcolor=\"#E9E8F9\"><BR><B>Comment from Neo:</B><BR><BR><FONT SIZE=2>This is where a comment might go.</FONT><BR><BR></TD></TR></TABLE><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/02/05 12:09:52am]</FONT>";

$posts[0][3] = "<B>Date:</B> 12:09:52am, Sunday January 2, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE border=0 width=\"600\"><TR><TD bgcolor=\"#B6BFE7\"><BR><B>Comment from Neo:</B><BR><BR><FONT SIZE=2>This is where a comment might go.</FONT><BR><BR></TD></TR></TABLE><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/02/05 12:10:40am]</FONT>";

$posts[0][3] = "<B>Date:</B> 12:10:40am, Sunday January 2, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>-------------------------------------------------------------------<BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/02/05 12:13:28am]</FONT>";

$posts[0][3] = "<B>Date:</B> 12:13:28am, Sunday January 2, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>.................................................................................<BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/02/05 12:15:18am]</FONT>";

$posts[0][3] = "<B>Date:</B> 12:15:18am, Sunday January 2, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>.........................................................................................................................................................<BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/02/05 12:15:50am]</FONT>";

$posts[0][3] = "<B>Date:</B> 12:15:50am, Sunday January 2, 2005";
?>

<?php
$post2 = array ("<B>Full Name:</B> Brian Bowden", "<B>Username:</B> <A HREF=../../users/u0000neo/user.php?profile=1><FONT COLOR=$secondarylinkcolor>nEo</FONT></A>", "<B>Position:</B> Administrator", "<B>Date:</B> 5:09:08pm, Monday January 3, 2005", "<B>Post #:</B> 2", "Today I bought a laser pointer, and it has made me the coolest guy on the block. After all, no one else on this street can make a red dot appear on something (looks at package) 1600 feet away! Now <I>that</I> is the epidomy of cool. If you don\'t think so, you must not have ever seen a laser pointer, because laser pointers rock the world off its foundation. Look for shots of me and my laser pointer in the news and in popular magazines everywhere.", "5:01:21pm, Monday January 3, 2005", "1104790148");
$posts[1] = $post2;
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE border=1 align=\"center\"><TR><TD><BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR></TD></TR></TABLE><BR><BR><BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:12:17pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:12:17pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE border=1 align=\"center\"><TR><TD bordercolor=black><BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR></TD></TR></TABLE><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:12:38pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:12:38pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE bgcolor=\"#800000\" align=\"center\"><TR><TD><BR><FONT SIZE=2><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR></TD></TR></TABLE><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:14:21pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:14:21pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><TABLE bgcolor=\"#800000\" align=\"center\" width=500><TR><TD><BR><FONT SIZE=2 color=\"white\"><B>Comment from Neo:</B><BR><BR>This is where a comment might go.<BR></FONT><BR></TD></TR></TABLE><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:14:54pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:14:54pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:16:51pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:16:51pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>..........................................................................................................................................<BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:18:10pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:18:10pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>..................................................................................................................................................................<BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:18:39pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:18:39pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>........................................................................................................................................................<BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:18:51pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:18:51pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR>................................................................................................................................................<BR><BR><BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:19:29pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:19:29pm, Monday January 3, 2005";
?>

<?php
$posts[0][5] = "I just realized that I had no journal entry or even a journal that existed, which is really not good considering this is my forum. I started a Xanga account so I could read the journals of others, but today I decided to write something in my own account just out of sheer boredom. I just don\'t want to get off the internet, but I don\'t have anything else to do. Well, I do have other things to do, I just don\'t want to do them. Plus, there\'s so much internet that you can\'t possibly get bored. I mean, if you\'re really bored from the same old sites that you visit every day, you should try some other sites that you\'ve never been to. Just search for something in Google. We\'re not the only people with a cool website. ;-D j/k Just be careful what you click on. I met some not-so-cool content in some sites while trying to find the perfect alternative sites for Syzito, and I don\'t think y\'all would want to run into the same thing. So be careful, and I\'ll try to do the same.<BR><BR>Let\'s see, are there any cool new sites that I\'ve been to that y\'all might be interested in? No. Are there any sites that I\'m going to tell y\'all about anyway? Yes! I went to the American Nazi Party website a few days ago. It\'s NOT a cool site. It\'s hard to believe that there are people who still believe that white people are the \"Chosen Ones\" and the whole Arian Brotherhood thing. You can order stuff like White Power posters, and posters that warn you about the danger of letting non-whites live in the United States. If I wasn\'t white I think I would be just a little offended. :-P<BR><BR>The Abrupt End<BR><BR><DIV ALIGN=\"Center\">...............................................................................................................................................</DIV><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><SPANYouWillNeverGuess><FONT SIZE=2>[Modified by <A HREF=../../users/u0000neo/user.php?profile=1>nEo</A> on 01/03/05 5:20:23pm]</FONT>";

$posts[0][3] = "<B>Date:</B> 5:20:23pm, Monday January 3, 2005";
?>
